# For documentation on settings, see https://github.com/apps/settings

repository:
  # For options, see https://docs.github.com/en/rest/reference/repos#update-a-repository

  # The name of the repository. Changing this will rename the repository
  name: landscape-graph

  # A short description of the repository that will show up on GitHub
  description: Landscape data --> Graph Database (Neo4j)

  # A URL with more information about the repository
  homepage: https://graph.cncf.io
  
collaborators:
  # For options, see https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator
  - username: caniszczyk
    permission: admin
  - username: jeefy
    permission: admin
  - username: chalin
    permission: admin
  - username: nate-double-u
    permission: admin
  - username: sftim
    permission: admin
  - username: halcyondude
    permission: admin
  - username: carolynvs
    permission: write

# Labels: define labels for Issues and Pull Requests
labels:
  - name: cleanup
    color: 1ebcd8
  - name: e0-minutes
    description: "Effort: < 60 min"
    color: e6ccb3
- name: e1-hours
    description: "Effort: < 8 hrs"
    color: d9b38c
  - name: e2-days
    description: "Effort: < 5 days"
    color: cc9966
  - name: e3-weeks
    description: "Effort: < 4 weeks"
    color: bf8040
  - name: e4-months
    description: "Effort: 1+ months"
    color: 996633
  - name: infrastructure
    color: 696969
  - name: p0-critical
    color: B60205
  - name: p1-high
    color: D93F0B
  - name: p2-medium
    color: FBCA04
  - name: p3-low
    color: FEF2C0
  - name: "Q for graph"
    description: Questions landscape-graph can inform
    color: 5319e7
  # GitHub default labels
  - name: bug
    description: "Something isn't working"
    color: d73a4a
  - name: documentation
    description: Improvements or additions to documentation
    color: 0075ca
  - name: duplicate
    description: This issue or pull request already exists
    color: cfd3d7
  - name: enhancement
    description: New feature or request
    color: a2eeef
  - name: good first issue
    description: Good for newcomers
    color: 7057ff
  - name: help wanted
    description: Extra attention is needed
    color: 008672
  - name: invalid
    description: "This doesn't seem right"
    color: e4e669
  - name: question
    description: Further information is requested
    color: d876e3
  - name: wontfix
    description: This will not be worked on
    color: ffffff
  
  # Sub-Graph Module (SGM) Component Labels
  # BLOGS
  - name: sgm/blogcncf
    description: "Sub-Graph Module: blogs/sgm-blogcncf"
    color: E8B4D9
  
  # BOARDS
  - name: sgm/ghdiscuss
    description: "Sub-Graph Module: boards/sgm-ghdiscuss"
    color: B4D9E8
  - name: sgm/stackoverflow
    description: "Sub-Graph Module: boards/sgm-stackoverflow"
    color: B4D9E8
  
  # CNCF & CORE
  - name: sgm/cncf
    description: "Sub-Graph Module: cncf"
    color: CCCCCC
  - name: sgm/core
    description: "Sub-Graph Module: core"
    color: CCCCCC
  
  # CORP
  - name: sgm/crunchbase
    description: "Sub-Graph Module: corp/sgm-crunchbase"
    color: D9E8B4
  - name: sgm/yahoofinance
    description: "Sub-Graph Module: corp/sgm-yahoofinance"
    color: D9E8B4
  
  # PACKAGES
  - name: sgm/brew
    description: "Sub-Graph Module: packages/sgm-brew"
    color: FFD580
  - name: sgm/choco
    description: "Sub-Graph Module: packages/sgm-choco"
    color: FFD580
  - name: sgm/crate
    description: "Sub-Graph Module: packages/sgm-crate"
    color: FFD580
  - name: sgm/deb
    description: "Sub-Graph Module: packages/sgm-deb"
    color: FFD580
  - name: sgm/deno
    description: "Sub-Graph Module: packages/sgm-deno"
    color: FFD580
  - name: sgm/go
    description: "Sub-Graph Module: packages/sgm-go"
    color: FFD580
  - name: sgm/maven
    description: "Sub-Graph Module: packages/sgm-maven"
    color: FFD580
  - name: sgm/npm
    description: "Sub-Graph Module: packages/sgm-npm"
    color: FFD580
  - name: sgm/pip
    description: "Sub-Graph Module: packages/sgm-pip"
    color: FFD580
  - name: sgm/rpm
    description: "Sub-Graph Module: packages/sgm-rpm"
    color: FFD580
  
  # RTC (Real-Time Communication)
  - name: sgm/discord
    description: "Sub-Graph Module: rtc/sgm-discord"
    color: B4E8D9
  - name: sgm/slack
    description: "Sub-Graph Module: rtc/sgm-slack"
    color: B4E8D9
  
  # SCM (Source Control Management)
  - name: sgm/gharchive
    description: "Sub-Graph Module: sgm-gharchive"
    color: D9B4E8
  - name: sgm/git
    description: "Sub-Graph Module: sgm-git"
    color: D9B4E8
  - name: sgm/github
    description: "Sub-Graph Module: sgm-github"
    color: D9B4E8
  - name: sgm/template
    description: "Sub-Graph Module: sgm-template"
    color: CCCCCC
  
  # SOCIAL
  - name: sgm/email
    description: "Sub-Graph Module: social/sgm-email"
    color: E8D9B4
  - name: sgm/linkedin
    description: "Sub-Graph Module: social/sgm-linkedin"
    color: E8D9B4
  - name: sgm/twitter
    description: "Sub-Graph Module: social/sgm-twitter"
    color: E8D9B4
  
  # THREATS
  - name: sgm/nist
    description: "Sub-Graph Module: threats/sgm-nist"
    color: FF9999
  
  # VIDEOS
  - name: sgm/youtube
    description: "Sub-Graph Module: videos/sgm-youtube"
    color: 99CCFF

